name: Release

on: 
  workflow_dispatch:
    inputs:
      tag:
        description: Version tag
        required: true

permissions:
  deployments: write
  packages: write
  contents: write

env:
  PACKAGE_DIR: pkg
  PACKAGE_RETENTION: 2
  PUB_DIR: pub
  SCRIPTS_PATH: ${{ github.workspace }}/nethermind/scripts/deployment

jobs:
  release:
    runs-on: ${{ matrix.target.host }}
    strategy:
      matrix:
        target:
          - arch: linux-x64
            host: ubuntu-22.04
          - arch: linux-arm64
            host: ubuntu-22.04
          - arch: osx-arm64
            host: macos-latest
          - arch: osx-x64
            host: macos-latest
          - arch: win-x64
            host: windows-latest
    steps:
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Publish for ${{ matrix.target.arch }}
      run: |
        dotnet publish Nethermind.KZGCli/Nethermind.KZGCli.csproj --self-contained -c Release -p:Version=${{ inputs.tag }} -o out --runtime ${{ matrix.target.arch }} /p:DebugType=None /p:DebugSymbols=false
        mv out/* 
    - name: Upload Release
      uses: ncipollo/release-action@v1.12.0
      with:
        path: out/
        artifacts: Kzg-${{ matrix.target.arch }}.zip
